# Generated by Django 5.2 on 2025-05-03 16:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='video',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='activity_image'),
        ),
    ]
